# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba7c2d59c36f78801253f570c3f8ddfb44a800867da96838dbaeb23bac6648bea6b0c2ccfb9935722ff83431c58879fb8ba444d9d4eef44bc0bc4abdf4d62690

test:
  secret_key_base: 056bda1095f688706f652d32a9853030889d2dcd6a4059cc632047e048895bed9b3c155d9ee4316823e911b6521f14d01678e49fcaedfc178342fa704dc08b99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
